### ISSUE TITLE
possible integration of check_redfish

### ISSUE THREAD

**Issue by bb-Ricardo** [Yogibaer75/Check_MK-Things#1]
Hi,

would you consider using https://github.com/bb-ricardo/check_redfish to use as library for your agent?

I just have no idea of how much work it would be to integrate it.

**Comment by Yogibaer75** [comment]
Hi Ricardo,
sorry for not answering your Issue. I got not so many issues until now. What do you mean directly with "using check_redfish for my agent"?
The iLO agent uses directly the redfish API from HP. It is possible that i migrate it to the generic redfish library if needed.
For Dell iDRAC i will use the generic redfish library.
In most of my environments i try to avoid any classic Nagios/Icinga check under all circumstances as they lack one of the most important features --> automatic service discovery.
All the agents produce here only raw data output that then later are processed from the CheckMK checks.

**Comment by bb-Ricardo** [comment]
Hi,

no worries. Thought it could help to integrate generic hardware monitoring but it seems the approaches here are too different.

And yes automatic service discovery makes sense in most environments.

Then I will close this issue for now.
