### ISSUE TITLE
Feature request: configure ip address to test against

### ISSUE THREAD

**Issue by sploenix** [Yogibaer75/Check_MK-Things#11]
Hi,

it would be very nice, if the ip address, which is used for the test, could be (optionally) configured. Right now we are using snmp for iDRAC monitoring, therefore we configure the snmp settings in host properties / management board. 
In a perfect world redfish would be a selectable option in the management board section of the host - but I don't know how hard this is to implement. 
As an alternative, an optional address field in the special agent configuration could solve this, so that the agent can be configured for the server itself, but checks against the ip of the iDRAC.

Kind regards
Sören

**Comment by Yogibaer75** [comment]
I think this will not be possible. Two points.
 - management board is the worst existing feature and the possibility that it will be deprecated and removed in the near future is high (i hope so) after some discussions at the last conference
 - a normal special agent should/must use the device IP it is assigned to

From a management standpoint it makes no sense to mix the hardware information with the operating system things.
But that is my personal opinion. :)

best regards
Andreas

**Comment by sploenix** [comment]
Ok did not know this. At least it makes no sense then to add iDRAC data using management board entry for new systems.
Can you point out, why this is the worst existing feature?

**Comment by Yogibaer75** [comment]
I will try some points.

Until the resent version of CMK all maintenance interface checks where extra checks. That means inside the CMK you had two checks doing the same, one time for management und one time for normal SNMP. --> Stupid
Second point was or is naming. Why do we have different names (prefix) for the management board compared to the normal checks.
Third rules, it is not clear and was also not before what rules are matching to the management interface. You need to do some trial and error.
Also a problem is the broken IPMI implementation on the management interface. Compare what you can configure for the normal IPMI special agent or the IPMI active check. Nothing from this is possible on the management interface. In bigger systems you need this flexibility as IPMI is very very different from manufacturer to manufacturer.
Last point what i have here is - no special agents possible in any way.

In this example here Redfish is the actual industry standard for hardware management supported from all hardware manufacturers. In my monitoring systems there is no SNMP or IPMI anymore to monitor the hardware infrastructure only special agents.

**Comment by DiscoveryOV** [comment]
Sorry to reopen this, just had a quick question: how do you suggest monitoring both iDrac and the host OS under the same "host" in checkmk, or is that not possible? Do I need a separate host for each?

Thanks

**Comment by tcatlas** [comment]
Sorry to add to this @Yogibaer75 , just had a quick question: how do you suggest monitoring both iDrac and the host OS under the same "host" in checkmk, or is that not possible? Do I need a separate host for each?

Thanks

**Comment by Yogibaer75** [comment]
Under the same "host" it is possible and i would advise to don't do this.
Please create a host object for the OS and one for the iDrac/iLO.
