### ISSUE TITLE
netapp_eseries_drives crash in version 2.1.X

### ISSUE THREAD

**Issue by himself1985** [Yogibaer75/Check_MK-Things#12]
Hey. I'm getting an crash report on all drives since i installed new version 2.1.x.
All other checks working fine.

**Comment by Yogibaer75** [comment]
It would be good to know what version of the mkp you use.
And for a real troubleshooting i would need to agent output and also the crash report.

**Comment by himself1985** [comment]
Version: netapp_eseries | 2.68
[Checkmk_Crash_greiff_c9990842-0838-11ed-8abe-57e7517f7e31_2022-07-20_14-34-20.tar.gz](https://github.com/Yogibaer75/Check_MK-Things/files/9150784/Checkmk_Crash_greiff_c9990842-0838-11ed-8abe-57e7517f7e31_2022-07-20_14-34-20.tar.gz)

[checkoutput.txt](https://github.com/Yogibaer75/Check_MK-Things/files/9150807/checkoutput.txt)

**Comment by himself1985** [comment]
Version: netapp_eseries | 2.68

[checkoutput.txt](https://github.com/Yogibaer75/Check_MK-Things/files/9150807/checkoutput.txt)

[Checkmk_Crash_c9990842-0838-11ed-8abe-57e7517f7e31_2022-07-20_14-34-20.tar.gz](https://github.com/Yogibaer75/Check_MK-Things/files/9150837/Checkmk_Crash_c9990842-0838-11ed-8abe-57e7517f7e31_2022-07-20_14-34-20.tar.gz)

**Comment by Yogibaer75** [comment]
This error is fixed in version 2.69
I don't know why it is not visible on the exchange - can be found here
https://github.com/chexma/checkmk_plugins/tree/master/netapp_eseries

**Comment by himself1985** [comment]
Ah okay, thanks a lot, works again.
Great job by you guys, thank you!
