### ISSUE TITLE
hpe_ilo 3.4 and 3.5 "Some GUI extensions could not be loaded"

### ISSUE THREAD

**Issue by 47k** [Yogibaer75/Check_MK-Things#16]
**CheckMK Version:** 2.1.0p10 CFE
**Plugin Version:** 3.4 and 3.5
**OS Version:** Debian 11 

Some GUI extensions could not be loaded. This may be caused by some incompatible extension packages.

Loading "/omd/sites/Test/local/share/check_mk/web/plugins/wato/datasource_programs_ilo.py" failed: cannot import name 'RulespecGroupDatasourcePrograms' from 'cmk.gui.plugins.wato.datasource_programs' (/omd/sites/Test/lib/python3/cmk/gui/plugins/wato/datasource_programs.py)

**Comment by Yogibaer75** [comment]
Should be fixed with version 3.6
It's nice that this is only broken from p9 to p10 :(
https://github.com/Yogibaer75/Check_MK-Things/commit/a7e2276c2ecc518d8f9dd4955085b2bf9e4749b5
