### ISSUE TITLE
Dell iDRAC Restful API Check Crash

### ISSUE THREAD

**Issue by jamespoore** [Yogibaer75/Check_MK-Things#17]
Hello,

Testing out this plugin and it's a great improvement over the older one. But I see a couple of checks which crash.

![image](https://user-images.githubusercontent.com/6298678/187098252-c9fcb754-64a8-4cc8-92c8-4c92cb10a41c.png)

OG Check:
![image](https://user-images.githubusercontent.com/6298678/187099461-1290ec34-f447-4c79-a0d8-cc3a1a3d09f2.png)

Storage Controller RAID.Integrated.1-1:
![image](https://user-images.githubusercontent.com/6298678/187098286-75587e01-80fe-4a27-9f20-15de807692c7.png)

Please let me know if I can provide any issue to help resolve. I'd like to deploy this check wider in my environment.

Thanks

**Comment by jamespoore** [comment]
Another thing I noticed:
![image](https://user-images.githubusercontent.com/6298678/187099112-308b97a9-4f1e-4899-8113-3db0908d41c1.png)

I am using RAID5.
![image](https://user-images.githubusercontent.com/6298678/187099133-6051d00d-9edd-43e6-a05a-877a64d52ec0.png)
![image](https://user-images.githubusercontent.com/6298678/187099475-b57eb657-9edf-472f-9768-7577bd1e6509.png)

**Comment by Yogibaer75** [comment]
Hi,

first one question. What version of the check do you use?
If it is 1.6, it would be good if you can sent me the crash report and if possible the original agent output.

In the screenshot with the stack trace from the array controller i see that my last change from version 1.6 is missing.
On the CheckMK Exchange 1.6 is not available at the moment as it is in review for some weeks :(
You can download the mkp here and test please.

br
Andreas

**Comment by jamespoore** [comment]
Hi Andreas,

Thank you for your very quick reply.

I was using v1.1 from the Exchange, after updating to your v1.6 the checks are all green now and not crashing. 

Raid level on the storage shows as blank but this is not what my original 'issue' was for so I suggest this is now closed :)

<img width="951" alt="Screenshot 2022-08-29 at 09 08 35" src="https://user-images.githubusercontent.com/6298678/187157639-acdf9cc4-b4f8-44be-b2f7-9ea31ca0ebae.png">

**Comment by Yogibaer75** [comment]
If a controller has no active raid or it is a AHCI controller then the output for the raid levels can be empty.
But i can only say in this case something if i can have a look at the agent output.
I will close this as with 1.6 the crashes are gone.
