### ISSUE TITLE
Issue after installing - HyperV Cluster Checks -

### ISSUE THREAD

**Issue by linomas** [Yogibaer75/Check_MK-Things#2]
I have got the following error message after uploading and installing the HyperV Cluster Checks mkp.

Some GUI extensions could not be loaded. This may be caused by some incompatible extension packages.

Loading "/omd/sites/<<site>>/local/share/check_mk/web/plugins/metrics/hyperv.py" failed: name 'df_translation' is not defined

I am using 1.6.0p19

Thanks in advance for help

**Comment by linomas** [comment]
I have add the folowing line at the begining of the file to import the module

from cmk.gui.plugins.metrics.check_mk import df_translation

**Comment by Yogibaer75** [comment]
Yes this import was missing. I will try to build an updated package today.

**Comment by linomas** [comment]
Thanks for your work.

**Comment by Yogibaer75** [comment]
I forgot to write that the updated package is now available.
