### ISSUE TITLE
HPE Ilo deprecated plugin 

### ISSUE THREAD

**Issue by 47k** [Yogibaer75/Check_MK-Things#20]
**OS**: Debian 11 
**CheckMK**: 2.1.0p12 CEE 

**Error:**
Deprecated plugin will be ignore in Checkmk version 2.2. (see werk #14084): ilo_firmware

**Comment by Yogibaer75** [comment]
This is no problem at the moment. I only need to migrate this inventory plugin at 2.2 release.
At the moment it is not so easy to migrate all plugins from legacy as there are already incompatible things between 2.0 and 2.1.
When 2.2 beta is available this will be migrated then only for systems from 2.2 upwarts.
All the 2.0 and 2.1 will work with the current version.
