### ISSUE TITLE
hpe_ilo and use different host

### ISSUE THREAD

**Issue by meilon** [Yogibaer75/Check_MK-Things#29]
Because HPEs IPMI implementation isn't where I would expect it, I'd like to try your hpe_ilo extension.

How would one configure it to use a different IP to check an existing host? CheckMK does have the "Management Board" options, before that I used a tag with a custom attribute for an external check. Your extension (from what I understand) expects its check to be called on a secondary "iLO" host, but I'd like the data to be combined in one host.

Would plugging into the "Management Board" feature be an option, if even possible, for a future release?

**Comment by Yogibaer75** [comment]
The management board function inside CMK is more than a little bit broken.
There is no chance to integrate normal special agents.
On all of my systems is the usage of this feature "prohibited".

**Comment by meilon** [comment]
If plugging into the management board feature isn't an option, would providing piggyback data be an option? iLO knows the hostname of the running OS, therefore just pushing the data onto that host should be possible.

**Comment by Yogibaer75** [comment]
I don't think that this will be an option that i will implement.
Technical it is possible but i will complicate the whole agent and this agent is complex enough.
