### ISSUE TITLE
attribution of credit for code - me4 array

### ISSUE THREAD

**Issue by ds-04** [Yogibaer75/Check_MK-Things#3]
Hi Yogibear75,

I came across your code (for Dell ME4 array) and have used some of it to produce a nagios compatible script which I plan to use with LibreNMS.

The repository will be here:

https://github.com/ds-04/dell_me4_array_nagios_check

I just wanted to make you aware of this and I will attribute credit to you.

thanks

**Comment by Yogibaer75** [comment]
No Problem as also my code is from different other checks inspired.
The information from the status calculations are from the official documentation.

br
Andreas
