### ISSUE TITLE
StorCLI on ESXI without Agent

### ISSUE THREAD

**Issue by nolyy1988** [Yogibaer75/Check_MK-Things#31]
Is it possible to get the StorCLI Checks from an ESXI v7 in CheckMK without the check_mk_agent?
What i found out, it is not possible to install the agent on ESXI.

I´m using check_mk 1.6p14, and tried to do it simple with a new rule and ssh command, but the interpretation doesn't work like that

Have you any idea how this can work?

Thanks
BR

**Comment by Yogibaer75** [comment]
If this is a general question for a CheckMK problem the CheckMK forum under https://forum.checkmk.com/
is a better place to ask.

**Comment by Yogibaer75** [comment]
Nothing to do with the repo.
