### ISSUE TITLE
sccm_status check for cmk 2.1

### ISSUE THREAD

**Issue by gregdent** [Yogibaer75/Check_MK-Things#34]
hi andreas - my SCCM engineer was interested to see if cmk can monitor SCCM, as we're having lots of issues with it after the latest release. I noticed you had written something for cmk 2.0, and was wondering if it worked in 2.1+?

was there a way to make a .mkp file from the python script you wrote? I have the ps1 file for the agent check, which seems to work fine, but was struggling to manually load the python scripts on the cmk server.

**Comment by Yogibaer75** [comment]
The file from the "checks" folder, you only need to put inside the "~/local/share/check_mk/checks/" folder in your site.
As i have no system to test anything with this plugin and checks, it is highly possible that i cannot do anything more with this check.
