### ISSUE TITLE
dell_powervault_me4-2.5.mkp incompatible with checkMK 2.2.0

### ISSUE THREAD

**Issue by Ronald-Kloust** [Yogibaer75/Check_MK-Things#35]
Hi Andreas,

up to yesterday our Distributed checkMK installation runs on version 2.1.0p28 and we're using your MKP dell_powervault_me4-2.5 to monitor a Dell Storage ME5024.

Today I updated our checkMK environment to current version 2.2.0 and the update process crashes. I saved the output in a textfile and found with the help of a checkMK supporter that the main reason is your MKP.

Here is the snipset of the error messages:
 
--- snip --- snip ---
  File "/omd/sites/ts_9/lib/python3/cmk/base/config.py", line 2784, in _make_source_args
    agent_configuration = info_func(params, hostname, ip_address)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/ts_9/local/share/check_mk/checks/agent_dellpowervault", line 20, in agent_dellpowervault_arguments
    args += " -u " + quote_shell_string(params["user"])
                     ^^^^^^^^^^^^^^^^^^
NameError: name 'quote_shell_string' is not defined

Traceback (most recent call last):
  File "/omd/sites/ts_9/lib/python3/cmk/base/cee/microcore_config.py", line 2136, in _hosts_worker
    hosts_data = _compute_worker_hosts_data(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/ts_9/lib/python3/cmk/base/cee/microcore_config.py", line 2027, in _compute_worker_hosts_data
    return [
           ^
--- snip --- snip ---

So it seems that the function quote_shell_string isn't defined and produces an error. After deleting the MKP the update process runs soomthly to the end.

I hope you can fix the issue and release a new version shortly.

Thank you in advance
Ronald Kloust

**Comment by Yogibaer75** [comment]
Hi Ronald,

as this mkp was made for 2.0 it is possible that some problems can occur with newer versions.
As i have no access to such Dell storage systems at the moment i can only test the parts that will work without agent data.

**Comment by Yogibaer75** [comment]
You can checkout this commit
https://github.com/Yogibaer75/Check_MK-Things/commit/b8f67a9da4ab186827953042906876319dfcbf21
Here the agent should work again with 2.2
