### ISSUE TITLE
Redfish Issue

### ISSUE THREAD

**Issue by pietro95** [Yogibaer75/Check_MK-Things#36]
Hello, I'm using Redfish plugin to monitor some HPE ILO's. 

CheckMk 2.1, Ubuntu 22.04, Plugin version 2.1.8.

I installed the plugin a couple of weeks ago and everything was working, now since a couple of day the plugin is not working. Doing the check test return this:

```
Agent exited with code 1: Traceback (most recent call last):
File "/omd/sites/mysite/local/share/check_mk/agents/special/agent_ilo", line 27, in <module>
from redfish.rest.v1 import ServerDownOrUnreachableError
ModuleNotFoundError: No module named 'redfish.rest.v1'
```

I tried reinstall the pip module without any success. Can you help me?

**Comment by Yogibaer75** [comment]
I can only check with my test system - CMK 2.1 - plugin hpe_ilo-3.7.mkp - Redfish library installed with `pip3 install 'urllib3<2' redfish`
There is no error message about not existing modules.

**Comment by Yogibaer75** [comment]
There must be a problem with the local installed Python libraries.
