### ISSUE TITLE
Upgrading Dell iDRAC Restful API Checks vs Redfish Restful API Checks

### ISSUE THREAD

**Issue by scotsie** [Yogibaer75/Check_MK-Things#38]
Just submitting a question regarding the two different MKP packages. 
Is the the Redfish Restful API Checks meant to fully replace the Dell iDRAC Restful API completely or work in conjunction with it?

We're using the Dell iDRAC extension to monitor several newer MX7000 chassis. I just updated it to 2.1.1

Initial testing with the universal Redfish extension doesn't seem to pull any new or additional data. Will happily provide data/output if desired.

Sincerely,
Scotsie

**Comment by Yogibaer75** [comment]
The Redfish plugin should replace the HPE iLO / Dell iDRAC / Lenovo XClarity und all other vendor specific checks for the management interfaces.
If you see i difference or some missing things with the Redfish agent it would be nice if you can report this problems.

**Comment by scotsie** [comment]
> The Redfish plugin should replace the HPE iLO / Dell iDRAC / Lenovo XClarity und all other vendor specific checks for the management interfaces. If you see i difference or some missing things with the Redfish agent it would be nice if you can report this problems.

Thank you. I'll do some testing and open an issue once I have some more firm results.
