### ISSUE TITLE
Problem with the Netapp E-Series Check

### ISSUE THREAD

**Issue by Cologran** [Yogibaer75/Check_MK-Things#39]
Hello!

We use the Netapp E-Series Check with the CheckMK RAW Edition version 2.2.0p6.

Since updating the NetApp to firmware version 11.80GA we get an error in CheckMK. SAS A-1 "Port status" is always set to "failed: WARN".

Exactly as described here: https://kb.netapp.com/onprem/E-Series/Hardware/E-Series%3A_Warning_SAS_Port_failed_on_monitoring_system_-_CheckMK

- We have not found any newer firmware for the NetApp. 
- The NetApp has also been rebooted, but without success.

**Comment by Yogibaer75** [comment]
Please open an issue in the correct Github repo.
https://github.com/chexma/checkmk_plugins/tree/master
This check is not maintained here.
