### ISSUE TITLE
dell_powervault_me4_v3.0.0 crashes on CMK 2.2.0p9 checking a DELL ME5024

### ISSUE THREAD

**Issue by Ronald-Kloust** [Yogibaer75/Check_MK-Things#40]
Hallo Yogibaer,
ich hoffe wir schreiben wir in Deutsch falls nicht bitte melden dann übersetze ich natürlich meinen Text.

Dein o.a. PlugIn produziert auf unserem "Distributed Environment" (Zentralinstanz + 9  Remote-Instanzen) unter CheckMK 2.2.0p9  einen Crashreport. Ich hab mal zwei Dateien zugefügt.

[dell_powervault_me4_v3_0_0_crashreport-f03cde29-68e1-11ee-88db-e50042b29ad6.pdf](https://github.com/Yogibaer75/Check_MK-Things/files/12880699/dell_powervault_me4_v3_0_0_crashreport-f03cde29-68e1-11ee-88db-e50042b29ad6.pdf)
[crash.txt](https://github.com/Yogibaer75/Check_MK-Things/files/12880705/crash.txt)

Unter dem 2.2.x Release scheint es auch Probleme mit der Verteilung des Extension Packages zu den Remote-Sites zu geben. Ich brauche hier Unterstützung.

Erreichbar bin ich unter Ronald.Kloust@dlr.de vormittags zwischen 09:00 und 13:00 Uhr.

Danke im Vaoraus
Ronald Kloust
DLR e.V.

**Comment by Yogibaer75** [comment]
Hallo Ronald,

das Problem sieht hier eher so aus, dass gar keine Daten von dem Gerät zurück kommen --> Section = {}
Denn Crash selbst kann ich abfangen für mehr Debugging wäre der komplette Agent Output für diesen Host notwendig.
Kannst ja bei Bedarf mir per Mail schicken.

Gruß
Andreas

**Comment by Yogibaer75** [comment]
Neue Version 3.1.0 vom mkp ist entweder hier oder in ein paar Tagen auf der CMK Exchange verfügbar.
Diese sollte nicht mehr crashen wenn keine Daten vorhanden sind.

Fixed mit https://github.com/Yogibaer75/Check_MK-Things/commit/1148903c5038d8067fdb2483f94c96c1f073a74b

**Comment by Ronald-Kloust** [comment]
Hallo Andreas,

 

danke für Deine Nachrichten zu meiner Meldung und der neuen Version des MKPs, die ich leider erst heute lesen konnte, da ich in den letzten Tagen nicht an meinem Arbeitsplatz war.

 

Ich werde das neue PlugIn herunterladen und installieren und sehen, warum das Gerät (Dell Speichersystem ME5024) keine Daten bereitstellt.

 

Danke für deine Unterstützung und bis bald

Ronald

 

Von: Andreas Döhler ***@***.***> 
Gesendet: Donnerstag, 26. Oktober 2023 08:03
An: Yogibaer75/Check_MK-Things ***@***.***>
Cc: Kloust, Ronald ***@***.***>; Author ***@***.***>
Betreff: Re: [Yogibaer75/Check_MK-Things] dell_powervault_me4_v3.0.0 crashes on CMK 2.2.0p9 checking a DELL ME5024 (Issue #40)

 

Hallo Ronald,

das Problem sieht hier eher so aus, dass gar keine Daten von dem Gerät zurück kommen --> Section = {}
Denn Crash selbst kann ich abfangen für mehr Debugging wäre der komplette Agent Output für diesen Host notwendig.
Kannst ja bei Bedarf mir per Mail schicken.

Gruß
Andreas
