### ISSUE TITLE
Redfish agent: [special_dell_idrac] The maximum number of user sessions is reached

### ISSUE THREAD

**Issue by stereu** [Yogibaer75/Check_MK-Things#41]
It seems that the agent is not using an opened session again but instead opens up a new one which leads to the error

[special_dell_idrac] The maximum number of user sessions is reached

This happens from time to time if iDRAC is not fast enough to close the inactive sessions.

**Comment by Yogibaer75** [comment]
Can you please check with the latest version of the "special_agent_redfish" this is the successor to all the agents for the single manufacturers. This one has session reuse included.

**Comment by stereu** [comment]
This solved it, thx Andreas!
