### ISSUE TITLE
[Improvement][Redfish] Dell NVMe SSDs missing

### ISSUE THREAD

**Issue by stereu** [Yogibaer75/Check_MK-Things#42]
NVMe SSDs connected via Front Bays in Dell Servers are missing in the new Redfish Plugin. The older iDRAC Plugin had those checks.

The Redfish endpoint for one drive is e.g. `/redfish/v1/Systems/System.Embedded.1/Storage/CPU.1/Drives/Disk.Bay.1:Enclosure.Internal.0-1`

Is this known and already in work or should i build and commit it to this repo?

**Comment by Yogibaer75** [comment]
Thanks for the information. I must have a look at my available systems if there is one with NVMe disks connected to the front bays. If it is not too much work and if possible for you i would also take an Redfish dump from such a machine for my dev work.
To make a dump from the Redfish interface i used the tool -->  https://github.com/DMTF/Redfish-Mockup-Creator
If you use this there are some folders included in Dell servers that can be removed from the output without problem.
<img width="438" alt="image" src="https://github.com/Yogibaer75/Check_MK-Things/assets/1856702/18fa92f8-9751-4494-8455-512bc490809d">
The marked folders are not needed and can be very big :)

**Comment by stereu** [comment]
Sure! Here you go: [dell-poweredge-r6515-redfish-dump](https://github.com/stereu/dell-poweredge-r6515-redfish-dump)
Access granted only for you and dev purposes as there are possibly sensitive informations in it.

**Comment by Yogibaer75** [comment]
Thanks for the dump. I think i saw already what is different between NVMe and normal drive.
I will test it and modify the agent with a new version the next days.

**Comment by Yogibaer75** [comment]
Strange i checked with my actual version 2.2.18 and i have the NVMe drives in the checks.
Also the volumes of these drives are shown correctly.
<img width="563" alt="image" src="https://github.com/Yogibaer75/Check_MK-Things/assets/1856702/31a4bada-34f3-42bb-83bc-2b425a0bebb9">
