### ISSUE TITLE
Redfish 2.1.17 plugin error  [special_redfish] Agent exited with code 1

### ISSUE THREAD

**Issue by scotsie** [Yogibaer75/Check_MK-Things#43]
Running into issues with the generic redfish module as a replacement for the Dell based plugin.

Running against newer Dell MX7000 Chassis hosts (x2).

1. Installed the MKP for 2.1.17 under Checkmk Managed Services Edition 2.1.0p28.
2. Confirmed redfish python module was already installed from previous dell_idrac_redfish v2.1.1 package.
3. Deleted old Dell based ruleset
4. Created new rule under "Dell iDRAC Management Controller" with credentials and options.

Check_MK inventory shows "[special_redfish] Agent exited with code 1: Caught unhandled AttributeError('NoneType' object has no attribute 'get') in /omd/sites/corpnms/lib/python3/cmk/special_agents/utils/agent_common.py:135CRIT"

Manually running agent_redfish with parameters and debug option shows same error,
```
OMD[corpnms]:~$ local/share/check_mk/agents/special/agent_redfish -P https --debug -u corpnms -s <PASSWORD> <HOSTNAME>
Traceback (most recent call last):
  File "/opt/omd/sites/corpnms/local/share/check_mk/agents/special/agent_redfish", line 429, in <module>
    sys.exit(main())
  File "/opt/omd/sites/corpnms/local/share/check_mk/agents/special/agent_redfish", line 425, in main
    return special_agent_main(parse_arguments, agent_redfish_main)
  File "/omd/sites/corpnms/lib/python3/cmk/special_agents/utils/agent_common.py", line 161, in special_agent_main
    _special_agent_main_core(parse_arguments, main_fn, argv or sys.argv[1:])
  File "/omd/sites/corpnms/lib/python3/cmk/special_agents/utils/agent_common.py", line 135, in _special_agent_main_core
    main_fn(args)
  File "/opt/omd/sites/corpnms/local/share/check_mk/agents/special/agent_redfish", line 415, in agent_redfish_main
    get_information(REDFISHOBJ, args.sections)
  File "/opt/omd/sites/corpnms/local/share/check_mk/agents/special/agent_redfish", line 256, in get_information
    manager_url = base_data.get("Managers").get("@odata.id")
AttributeError: 'NoneType' object has no attribute 'get'
```
Testing with Postman using those credentials and /redfish/v1/Managers shows:
```
{"error":{"code":"Base.1.0.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information.","@Message.ExtendedInfo":[{"MessageId":"CGEN1006","RelatedProperties":[],"Message":"Unable to complete the request because the resource URI does not exist or is not implemented.","MessageArgs":[],"Severity":"Critical","Resolution":"Enter a valid URI and retry the operation."}]}}
```
Testing with /redfish/v1/Chassis shows results.
```
{"@odata.context":"/redfish/v1/$metadata#ChassisCollection.ChassisCollection","@odata.type":"#ChassisCollection.ChassisCollection","@odata.id":"/redfish/v1/Chassis","Description":"Chassis Collection","Name":"Chassis Collection","Oem":null,"Members@odata.count":11,"Members":[{"@odata.id":"/redfish/v1/Chassis/Members('25022')"},{"@odata.id":"/redfish/v1/Chassis/Members('26318')"},{"@odata.id":"/redfish/v1/Chassis/Members('26319')"},{"@odata.id":"/redfish/v1/Chassis/Members('94059')"},{"@odata.id":"/redfish/v1/Chassis/Members('94062')"},{"@odata.id":"/redfish/v1/Chassis/Members('94049')"},{"@odata.id":"/redfish/v1/Chassis/Members('26331')"},{"@odata.id":"/redfish/v1/Chassis/Members('26329')"},{"@odata.id":"/redfish/v1/Chassis/Members('26321')"},{"@odata.id":"/redfish/v1/Chassis/Members('26320')"},{"@odata.id":"/redfish/v1/Chassis/Members('94052')"}]}
```
Guessing this is a host vs chassis data return issue.

Sincerely,
Scotsite

**Comment by scotsie** [comment]
As an additional note, the service root (/redfish/v1) response on a Dell MX7000 IDRAC is as follows:
```
{
    "@odata.context": "/redfish/v1/$metadata#ServiceRoot.v1_2_0.ServiceRoot(TelemetryService(),EventService(),CertificateService(),CompositionService(),AccountService(),Chassis(),Systems(),SessionService(),Registries())",
    "@odata.type": "#ServiceRoot.v1_2_0.ServiceRoot",
    "@odata.id": "/redfish/v1",
    "Oem": {
        "Dell": {
            "@odata.context": "/redfish/v1/$metadata#EID_674ServiceRoot.ServiceRoot(NetworkService(),ManagementDomainService(),ProfileService(),TemplateService(),IdentityPoolService(),NetworkConfigurationService(),ApplicationService(),AccountService(),OIDCClient(),UpdateService(),GroupService(),JobService(),DeviceService(),SearchService(),SessionService(),AlertService())",
            "@odata.type": "#EID_674ServiceRoot.ServiceRoot",
            "@odata.id": "/api",
            "NetworkService": {
                "@odata.id": "/api/NetworkService"
            },
            "ManagementDomainService": {
                "@odata.id": "/api/ManagementDomainService"
            },
            "ProfileService": {
                "@odata.id": "/api/ProfileService"
            },
            "TemplateService": {
                "@odata.id": "/api/TemplateService"
            },
            "IdentityPoolService": {
                "@odata.id": "/api/IdentityPoolService"
            },
            "NetworkConfigurationService": {
                "@odata.id": "/api/NetworkConfigurationService"
            },
            "ApplicationService": {
                "@odata.id": "/api/ApplicationService"
            },
            "AccountService": {
                "@odata.id": "/api/AccountService"
            },
            "OIDCClient": {
                "@odata.id": "/api/OIDCClient"
            },
            "UpdateService": {
                "@odata.id": "/api/UpdateService"
            },
            "GroupService": {
                "@odata.id": "/api/GroupService"
            },
            "JobService": {
                "@odata.id": "/api/JobService"
            },
            "DeviceService": {
                "@odata.id": "/api/DeviceService"
            },
            "SearchService": {
                "@odata.id": "/api/SearchService"
            },
            "SessionService": {
                "@odata.id": "/api/SessionService"
            },
            "AlertService": {
                "@odata.id": "/api/AlertService"
            }
        }
    },
    "Id": "RootService",
    "Description": "Redfish ServiceRoot",
    "Name": "Root Service",
    "Links": {
        "Sessions": {
            "@odata.id": "/redfish/v1/SessionService/Sessions"
        },
        "Oem": {
            "Dell": {
                "@odata.id": "/redfish/v1/Oem/Dell/LicenseManager"
            }
        }
    },
    "RedfishVersion": "1.2.0",
    "UUID": null,
    "TelemetryService": {
        "@odata.id": "/redfish/v1/TelemetryService"
    },
    "EventService": {
        "@odata.id": "/redfish/v1/EventService"
    },
    "CertificateService": {
        "@odata.id": "/redfish/v1/CertificateService"
    },
    "CompositionService": {
        "@odata.id": "/redfish/v1/CompositionService"
    },
    "AccountService": {
        "@odata.id": "/redfish/v1/AccountService"
    },
    "Chassis": {
        "@odata.id": "/redfish/v1/Chassis"
    },
    "Systems": {
        "@odata.id": "/redfish/v1/Systems"
    },
    "SessionService": {
        "@odata.id": "/redfish/v1/SessionService"
    },
    "Registries": {
        "@odata.id": "/redfish/v1/Registries"
    }
}
```

**Comment by Yogibaer75** [comment]
Ok the old Dell Redfish agent would not fetch the manager URI.
You can test with the new version [2.1.19](https://github.com/Yogibaer75/Check_MK-Things/blob/master/check%20plugins%202.1/redfish/redfish-2.1.19.mkp) / [2.2.19](https://github.com/Yogibaer75/Check_MK-Things/blob/master/check%20plugins%202.2/redfish/redfish-2.2.19.mkp). This should fix your problem.
If there are further problems (also bigger ones) it would be nice if you can use the 
https://github.com/DMTF/Redfish-Mockup-Creator
to create a dump from your Redfish interface and i can use it then for troubleshooting.

**Comment by scotsie** [comment]
Downloaded 2.1.19 and updated. No longer getting the Agent exited with code 1 and discovery is completing.

It does not appear to be outputting PSU or Fan information even though it is selected in the WATO GUI. It is showing an abundant amount of services for each sled/host such as CPU, Memory and Storage.

I cloned the Redfish-Mockup-Creator and have run it against one of our MX7000 hosts. I can see PSU info in the Chassis > Members(ID) tree. Attaching it here. 
[cha2-ip-output.zip](https://github.com/Yogibaer75/Check_MK-Things/files/13757996/cha2-ip-output.zip)

If you prefer some other method I'll edit and can provide some other method. If you prefer a new issues, I can create one and attach their instead.

Also, I appreciate your work on this and hope you have happy holiday(s).

**Comment by scotsie** [comment]
As a follow up, it seems that the plugin works but has sporadic failures for specific subsections redfish_fans, redfish_psu and redfish_temperature marking them as vanished for a time before they eventually repopulate.
"Memory Summary" and "System State" are not affected by this so I don't think the entire check is failing.

Approximately 5 minutes ago
![image](https://github.com/Yogibaer75/Check_MK-Things/assets/31043147/2420936e-0a3f-441a-89ea-72ec52dd5ed9)

And just now it refreshed with successful data
![image](https://github.com/Yogibaer75/Check_MK-Things/assets/31043147/4b1464ea-7ef0-45e3-a4eb-273014c0c251)

**Comment by Yogibaer75** [comment]
Thanks Scott for the info. If these parts are missing then the complete "chassis" section cannot be fetched.
Today i made some changes inside my dev system to test the different problem messages and how they can be forwarded to CMK.
It is working already for complete connection problems. But for a case like your one i need to dig a little bit depper.

In your case it could also be a problem with the long execution time. But i don't know how to make it better.

One idea i had is the following. You can comment what you think about it.
#######
The agent fetches every section as it is done now. Inside the state file for the connection also this output is saved.
You as a user or the agent itself can define a cache interval for every section and checks now at the second run for every section if this should be fetched. It could remove a huge load for checks that have no performance data (like memory modules) and it needs to fetch this only every 10-15 minutes or so. Or you define a higher cache interval for not so important items.

**Comment by scotsie** [comment]
> The agent fetches every section as it is done now. Inside the state file for the connection also this output is saved. You as a user or the agent itself can define a cache interval for every section and checks now at the second run for every section if this should be fetched. It could remove a huge load for checks that have no performance data (like memory modules) and it needs to fetch this only every 10-15 minutes or so. Or you define a higher cache interval for not so important items.

I think this sounds like an acceptable compromise. Robotmk does something similar I think and alerts on staleness.
If I can provide other info or test anything for you please feel free let me know.

**Comment by Yogibaer75** [comment]
I will first fix the problem with the multi systems. I have already some ideas how to handle this on the CheckMK side.
But need some time to make it working :)

**Comment by Yogibaer75** [comment]
Hi Scott, some good news i have now a version what can handle your blade chassis a little bit better.
<img width="780" alt="image" src="https://github.com/Yogibaer75/Check_MK-Things/assets/1856702/8d96db01-ae10-41e5-9c7b-e773ca914a84">
It is not perfect but i think better than before.
A version for 2.1 i will build the next days. At the moment only 2.2 and 2.3alpha is available.
https://github.com/Yogibaer75/Check_MK-Things/tree/master/check%20plugins%202.2/redfish

**Comment by Yogibaer75** [comment]
The problem with temperature/PSU/fan i also found.
There will be a fix also included.

**Comment by Yogibaer75** [comment]
@scotsie Now also 2.1 version for the actual state of the agent is available.

**Comment by scotsie** [comment]
Much appreciated, I pulled down v2.1 to test and saw your mention on the CheckMK forums as well.
I've enabled it for 1 chassis and will monitor for timeouts.
Since the original issue was with exit code 1 and the management interface, I will mark this issue as closed and follow up with a new issue if needed for timeouts.
PM me here or in the CheckMK forums if you need me to collect any more data for you outside of a new issue.
