### ISSUE TITLE
Redfish 2.2.19 / Fujitsu iRMC Support

### ISSUE THREAD

**Issue by MBEntain** [Yogibaer75/Check_MK-Things#44]
I'm currently running CMK 2.2.0p17 and the Redfish 2.2.19 Plugin.
For HPE iLO and Dell iDRAC everything is running fine.

I know that there is no Fujitsu support mentioned in the documentation, but I have seen a section for Fujitsu in the agent file "agent_redfish": 

```
if vendor_string in ["Hpe", "Hp"]:
        vendor_data = VendorHPEData()
        manager_data = root_data.get("Oem", {}).get(vendor_string, {}).get("Manager", {})[0]
        if manager_data:
            vendor_data.ilo_version = manager_data.get("ManagerType")
            if vendor_data.ilo_version is None:
                vendor_data.ilo_version = root_data.get("Oem", {}).get(vendor_string, {}).get("Moniker", {}).get("PRODGEN")
            vendor_data.ilo_firmware_version = manager_data.get("ManagerFirmwareVersion")
            if vendor_data.ilo_firmware_version is None:
                vendor_data.ilo_firmware_version = manager_data.get("Languages", {})[0].get("Version")
            if vendor_data.ilo_version.lower() == "ilo 5":
                vendor_data.view_supported = True
    elif vendor_string in ["Lenovo"]:
        vendor_data = VendorLenovoData()
    elif vendor_string in ["Dell"]:
        vendor_data = VendorDellData()
    elif vendor_string in ["Huawei"]:
        vendor_data = VendorHuaweiData()
    elif vendor_string in ["ts_fujitsu"]:
        vendor_data = VendorFujitsuData()
    elif vendor_string in ["Ami"]:
        vendor_data = VendorAmiData()
    elif vendor_string in ["Supermicro"]:
        vendor_data = VendorSupermicroData()
    elif vendor_string in ["Cisco"]:
        vendor_data = VendorCiscoData()
    else:
        vendor_data = VendorGeneric()
```

Is there anything to consider here, or does this implementation not yet work?

**Comment by Yogibaer75** [comment]
Fujitsu should work like all the other vendors you see there.
It means only that the plugin don't know any vendor specific settings like the one things there.

In general all vendors that support Redfish should work with this plugin.

**Comment by MBEntain** [comment]
HPE and Dell works fine, but for Fujitsu I'm receiving:
`Max retries exceeded with url: /redfish/v1 (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1006)')))]`

All different vendor devices are using self signed certificates.
Fujitsu test:
![grafik](https://github.com/Yogibaer75/Check_MK-Things/assets/104419000/238337ac-c942-484b-918c-d99805e2ace8)

Update:
The latest iRMC S4 Firmware solved the above issue.
Discovery works partially, as the management interface is very slow and therefore causes timeouts.
However, this is not a plugin problem.

**Comment by MBEntain** [comment]
I've tested the plugin for Dell, HPE and Fujitsu hosts now and there are no storage drives discovered for any vendor.
Only storage related check/information is about "Storage Controller".
May you have any information or hints for troubleshooting here?

Update:
HPE Drives can be discovered with enabling "HPE Storagesubsystem".
Dell and Fujitsu drives are missing as mentioned above.

**Comment by Yogibaer75** [comment]
Today i finished a new improved version. Storage device detection was the main thing.
Can you please check.
https://github.com/Yogibaer75/Check_MK-Things/tree/master/check%20plugins%202.2/redfish

**Comment by MBEntain** [comment]
Hi again,

I've imported the new version 2.2.31 and the drives got discovered.
Many thanks for the udpate!
