### ISSUE TITLE
[Feature Request] Don't collect piggyback data in Nutanix Plugin

### ISSUE THREAD

**Issue by vFabse91** [Yogibaer75/Check_MK-Things#48]
We are currently using the nutanix Plugin on checkmk version 2.2.
Everything is working quite good without any bigger problem. Thanks therefore

Due to an incident we found out, that there are many API Logins from checkmk (more than 1 Million per Day) over all our clusters (30 Clusters with more than 125 Hosts and more than 4000 VMs). 
I did some research and we found out, that the piggyback data for all hosts and virtual machines are collected - is this the reason for the amount of Logins? Is there a way to prevent the plugin to collect all this data (we don't need it for all the virtual machines).
I understand that collecting the piggyback is a good feature and will give many benefits to some users, but for us it's to much overload.
We are using the plugin only for checking our cluster health, the storage and the protection domains.

Regards Fabian

**Comment by Yogibaer75** [comment]
The easiest way would be to modify the Nutanix special agent.
Starting with line 138 you see all the sections that are fetched.
If you comment the "output_vms..." line no VM data is fetched.

br
Andreas

PS: to avoid login spam it is needed to change the login from simple username password to something like session login.

**Comment by Yogibaer75** [comment]
With the integration of the Nutanix plugin into CMK directly i will not make any bigger changes to the existing plugin.
Only if there are real errors.
