### ISSUE TITLE
redfish-2.3.33.mkp can not be activated with v2.3.0b3-rc1

### ISSUE THREAD

**Issue by okin** [Yogibaer75/Check_MK-Things#50]
After activating the plugin the GUI shows:

```
Some GUI extensions could not be loaded. This may be caused by some incompatible extension packages.

Loading "rulespec/redfish" failed: module 'cmk.rulesets.v1.form_specs.validators' has no attribute 'InRange'
```

It seems like commit 43a38d074f455352c428850e8c8b7bd8058731fa reverted the changes made by fd1517f306d8ebe1a437c23605b7663e1acc749f and results in this error.

**Comment by systeembeheerder** [comment]
<del></del>

sorry misread the version number.

**Comment by okin** [comment]
My issue is with `2.3.33`, which is supported until `2.3.99`.

**Comment by Yogibaer75** [comment]
This was already fixed and overwritten by myself :(
Fixed now with mkp version 2.3.34

**Comment by Yogibaer75** [comment]
One more remark - the "NumberInRange" is not available in b3 it will be in b4.
At the moment with b3 this will not work.
Daily builds are broken from my perspective at the moment.

**Comment by okin** [comment]
I tested with a daily build from last week and assumed the changes already have been present in the b3. Sorry for the version confusion.

Thank you for having a look at this!
