### ISSUE TITLE
Dealing_with_timeouts

### ISSUE THREAD

**Issue by olni** [Yogibaer75/Check_MK-Things#57]
...i'm really happy with your plugin and i switched a lot of machines from snmp to redfish. :-)
On one machine i got crash reports from time to time.

The decoded error message is:
`cause_exception': ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='192.168.168.9', port=443): Read timed out. (read timeout=3)"`

Is there a best practice or a workaround to deal witch such an error? Or just raise the amount of attempts?

Thanks in advance

Oliver

**Comment by Yogibaer75** [comment]
It is hard to say what will help here. I would only try with the "timeout" value of the special agent if this helps.
The maximum value you can select is 20 seconds. But this value should only be used for testing.
Is this problem machine one with many disks or many RAM modules?
Booth can slow down the retrieval of data. In such a case i switch of the memory module data collection and only use the memory summary status. This should also show me if there is a memory problem.

For drives i have no summary status found to avoid such a timing problem.

b.r
Andreas
