### ISSUE TITLE
No iLO data in CheckMK version 2.3.0p5

### ISSUE THREAD

**Issue by SuperHic** [Yogibaer75/Check_MK-Things#61]
After the upgrade to version 2.3.0p5 of CheckMK we don't have any iLO related data in the module section of any monitored hosts with iLO functionality. 

![Screenshot from 2024-06-12 14-46-49](https://github.com/Yogibaer75/Check_MK-Things/assets/41508787/c1b8aa2f-8a8f-4cb3-9798-11a3449480f5)

In the console we can see that the plugin is deprecated (As seen on the picture). 

Could you please inform us when will be the next release of this plugin, supporting the new CheckMK version 2.3.0p5? 

Thank you!

**Comment by Yogibaer75** [comment]
If you take a look inside the mkp description or on the github page, you will see that the vendor specific special agents are discontinued and are replaced with the generic Redfish agent.

from the readme.md
```
Redfish API checks for HPE iLO interfaces
!!! This package is obsolete please use the redfish package here

https://github.com/Yogibaer75/Check_MK-Things/tree/master/check%20plugins%202.2/redfish

!!! Starting with 2.3.0 the redfish package is also included inside CMK
```
