### ISSUE TITLE
Aditional value "redidual current" (Ableitstrom)

### ISSUE THREAD

**Issue by nightwatcher74** [Yogibaer75/Check_MK-Things#63]
Hi Yogibear75,

is it possible to add the residual current (Ableitstom) to the values? for this I wrote an SNMP check but it would be better to have an integrated check in redfish because we would move to that check as soon as possible. 

We are using Raritan PDUs (PX3-1528-M5P1) who will provide this on the  input/inlet side and have no outlet information (exept the names but no voltage/current etc.)

This is important for us because there is no requirements for yearly measurments from the electricans. 

There should also be an configurable warn/cirt value (devault: None/30mA)

As I heard on the conference you are in close contact with checkmk.. so I hove it will be possible to intergrate that :)

Thanks
Frank

**Comment by Yogibaer75** [comment]
At the moment i have only one dump from a Raritan PDU. This one is only single phase and i cannot find the wanted value there.
The type is PX4-559A-E8 if i remember correctly.
It would be very nice if you could provide a Redfish dump created with https://github.com/DMTF/Redfish-Mockup-Creator
You can also sent me this to my mail or provide a link to download it.

If your dump has also the wanted value it would be not so complicated to include it inside a check.

**Comment by nightwatcher74** [comment]
Hi Andreas,

at the attachment you can find the rum from the PDUs we are using.
PDU-Modell: PX3-1528-M5P1
Firmware: 4.2.0.5-50274

This PDU Series have no output values per socket only per fuse (3x6 fuses) and the overall values and the rsidual current

[PX3-1528-M5P1.tar.gz](https://github.com/user-attachments/files/15873727/PX3-1528-M5P1.tar.gz)

![input](https://github.com/Yogibaer75/Check_MK-Things/assets/12713048/c042d111-5ad0-496f-96dd-5ff32a333214)


Thanks 
Frank

**Comment by Yogibaer75** [comment]
The data looks good but i cannot find anywhere the data you want ☹️ 
There are no fuses in the output only 6 branches with data like this.
```
    "Id": "C1",
    "BreakerState": "Normal",
    "CircuitType": "Branch",
    "RatedCurrentAmps": 16.0,
    "UserLabel": "",
    "Status": {
        "State": "Enabled",
        "Health": "OK",
        "HealthRollup": "OK"
    },
    "CurrentAmps": {
        "Reading": 0.615
    },
```
1 main and 24 outlets.
The main data is a little bit more but also no residual current.
At the moment i would say the data is not available inside the Redfish provided data.
