### ISSUE TITLE
Nutanix Prism special agent for CMK - Cluster CPU and Memory?

### ISSUE THREAD

**Issue by armada-lmt** [Yogibaer75/Check_MK-Things#64]
We are finally upgrading our CMK from 1.6 to 2.x... we got to 2.0 so far and had to find a new Nutanix agent.   We're running version 3.6-2.0 of yours right now and the only thing that seems to be missing that we used on our old agent is "cluster CPU" and "cluster Memory".  I see that you report Host CPU and Memory for each host, so I guess we can figure out the overall Cluster CPU and Memory from those.. .but it would be nice to have the overall Cluster CPU and Memory on the cluster host itself.

For an example of what I mean, see the screenshot.. the CPU and Memory services are the CVM itself.  The NTNX CPU and Memory services are the overall/combined metrics for all hosts in the cluster.

![image](https://github.com/Yogibaer75/Check_MK-Things/assets/91284680/d83459ef-58b7-4b09-9ccc-9f2a9fa130ac)

**Comment by Yogibaer75** [comment]
As this is a very old version of the new special agent for Nutanix i cannot say what is the problem in your system.
Here is small screenshot from the checks with the actual version that is included with 2.3 of CheckMK.
![image](https://github.com/Yogibaer75/Check_MK-Things/assets/1856702/842c5009-e3e0-43a6-9e76-92f1c8fef485)
The latest version for 2.2 also gives the same output.
https://github.com/Yogibaer75/Check_MK-Things/blob/master/check%20plugins%202.2/nutanix/nutanix_prism-5.0.9.mkp

**Comment by armada-lmt** [comment]
Thanks for this information.  Looks like we just need to finish upgrading to 2.3 or at last 2.2.

**Comment by Yogibaer75** [comment]
2.1 should also be fine and nearly the same output.
