### ISSUE TITLE
'Netapp E-Series Checks' plugin fails to discover storages, after an update from 11.80GA to 11.80.1GA of Satricity System Manager

### ISSUE THREAD

**Issue by AdriM78** [Yogibaer75/Check_MK-Things#66]
[API_list_Eseries_11.80.1GA.txt](https://github.com/user-attachments/files/16311728/API_list_Eseries_11.80.1GA.txt)
Hi,

After an Eseries Santricity update from 11.80GA to 11.80.1GA, the package Netapp E-Series Checks doesn't work anymore.
https://exchange.checkmk.com/p/netapp-eseries

We get this errors below for each Eseries Storage:
[CRIT] Check_MK Discovery
no unmonitored services found, 107 vanished services ( .... ) , no new host labels, [special_netappeseries] Agent exited with code 1: Traceback (most recent call last):

Agent
Retry this test
Agent exited with code 1: Traceback (most recent call last):
File "/omd/sites/MYSITE/lib/python3.9/site-packages/requests/models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
File "/omd/sites/MYSITE/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/omd/sites/MYSITE/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/omd/sites/MYSITE/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/omd/sites/MYSITE/share/check_mk/agents/special/agent_netappeseries", line 501, in <module>
main()
File "/omd/sites/MYSITE/share/check_mk/agents/special/agent_netappeseries", line 497, in main
fetch_storage_data(session, sections, args, base_url, controller_ids)
File "/omd/sites/MYSITE/share/check_mk/agents/special/agent_netappeseries", line 153, in fetch_storage_data
section_perfdata = session.get(base_url + section.perfdata_uri,
File "/omd/sites/MYSITE/lib/python3.9/site-packages/requests/models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In order to fix partially the issue, we need to comment these lines below in agents.tar and netapp_eseries-3.0.2 files:
Section(
            name="controllers",
            uri="/controllers",
            perfdata_uri="/analysed-controller-statistics",
            perfdata_identifier="controllerId",
        ),

In 11.80.1GA the API  « /analysed-controller-statistics »  seems not exist anymore :/

So, after comments, in TMT the Controler A and Controler B (with serial number, status "optimal" etc) are "grey", and are not rediscovered correctly.

In attachment the API list in 11.80.1GA for Eseries.

Thx,
Adrien

**Comment by Yogibaer75** [comment]
Please open the issue here.
https://github.com/chexma/checkmk_plugins/tree/master
The repo is not on my site anymore.
What is very important for a bug report and missing in your description is --> CheckMk version and MKP version you use.
