### ISSUE TITLE
Why "Temp" and not "Temperature"?

### ISSUE THREAD

**Issue by gurubert** [Yogibaer75/Check_MK-Things#67]
Hi Andreas,

the redfish temperature checks (at least in 2.2.51) all start with "Temp" and also end in "Temp".
The old SNMP based checks on the same management board (Dell iDRAC) started with "Temperature" and did not end in "Temp".

It would be good if all temperature checks start with "Temperature" which would make them more consistent accross all of Checkmk. Second if the name would not change then the RRD could still provide metric data.

**Comment by Yogibaer75** [comment]
Oh this is only in 2.2 package existing. The 2.3 package looks ok.
That can be changed to have the same names as the 2.3. The naming there was coordinated with the CMK team.
The temp at the end is completely different as this is part if the sensor name inside the data provided by the system.
Here some examples.
Dell
<img width="177" alt="image" src="https://github.com/user-attachments/assets/63004cbb-137f-4290-b2a9-cab2a63d89bf">
<img width="172" alt="image" src="https://github.com/user-attachments/assets/c88487ed-8e23-4aa8-aed0-17f4fd63f471">
Cisco
<img width="157" alt="image" src="https://github.com/user-attachments/assets/5cc7ad6b-b734-41ed-9606-22e9d835ba42">
Fujitsu
<img width="103" alt="image" src="https://github.com/user-attachments/assets/77252a91-b2a3-4f04-a1d9-1807e7f0cc68">
HPE - Number is only used here extra as there are sensors with the same name
<img width="138" alt="image" src="https://github.com/user-attachments/assets/c0890e65-f440-439d-84dd-3c49639216d6">
There are more nice names available.

**Comment by Yogibaer75** [comment]
I see i must back port the last additions and changes from 2.3 to 2.2 :)

**Comment by Yogibaer75** [comment]
should be fixed now with commit e25ba29
Version 2.2.52 is then also uploaded to exchange
