### ISSUE TITLE
Redfish 2.3.52 Error: [special_redfish]: ModuleNotFoundError: No module named 'redfish.messages'

### ISSUE THREAD

**Issue by stereu** [Yogibaer75/Check_MK-Things#68]
Error: [special_redfish]: ModuleNotFoundError: No module named 'redfish.messages'
in the current version of your redfish module 2.3.52.

**Comment by Yogibaer75** [comment]
This error happens with CMK 2.3 if you had before installed the Redfish lib with "pip3 install redfish".
As the lib is now included with CMK you don't need this manual installed lib anymore.
Please have a look at "~/local/lib/python3/" if there is a "redfish" folder, please remove it.

**Comment by stereu** [comment]
Thanks! Now i am getting "redfish.rest.v1.RetriesExhaustedError" on all nodes.

**Comment by Yogibaer75** [comment]
What CMK version do you use?
The installed package "2.3.52" is for CMK 2.3
The following output is as site user inside python3

```
OMD[cmk]:~$ python3
Python 3.12.3 (main, May  7 2024, 15:13:53) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from redfish.rest.v1 import (
...     RetriesExhaustedError,
...     ServerDownOrUnreachableError,
...     JsonDecodingError,
... )
>>> 
```
No error message.
