### ISSUE TITLE
Redfish 2.3.52: HPE MSA storrage array old firmware activation Warning

### ISSUE THREAD

**Issue by slano** [Yogibaer75/Check_MK-Things#69]
Hey,

we're using Redfhish plugin version 2.3.52 to monitor HEP MSA 2060 Storage array. After upgrading the controller firmware, old firmware is still present in the MSA and it is possible to activate the old firmware (for example rollback purposes), but this situation triggers a Warning, even though the latest installed firmware is activated on controllers:

![image](https://github.com/user-attachments/assets/e51651d0-82d0-40cd-8002-f87f8fe04736)

State of the firmware on the MSA:
![image](https://github.com/user-attachments/assets/550ce7b4-27ba-4ebd-9484-0980410340eb)

If this behavior is as intended, please feel free to close the issue.

**Comment by Yogibaer75** [comment]
Ok i had no data from such a device for testing.
For this i need to modify the check a little bit, that a not active version is shown as ok.

**Comment by Yogibaer75** [comment]
fixed with 6451547 
new package 2.3.53 available

**Comment by slano** [comment]
Thanks Andreas! Upgraded to 2.3.53, works like a charm.

**Comment by Yogibaer75** [comment]
First i wanted to make an output if the actual version is active or not. But the bundle versions in you screenshot are strange.
Newer Version has a "alphabetical lower" version string than the older one.

**Comment by slano** [comment]
It is indeed strange, but **IN210R004** has been superseded by **IN210P001**:
![image](https://github.com/user-attachments/assets/605b50ed-cf34-46a3-a74e-fdeece8f32f0)

**Comment by Yogibaer75** [comment]
Then i will leave it as it is. Inactive firmware is every time ok.
