### ISSUE TITLE
Dell/EMC Powervault ME4 - Internal error: static_checks:dell_powervault_me4_*

### ISSUE THREAD

**Issue by raafcioo** [Yogibaer75/Check_MK-Things#70]
Hi,

We are using the Dell/EMC PowerVault ME4 plugin version 3.3.1 with the latest Checkmk Raw Edition 2.3.0p10 extensions.

It does not allow us to check the "Parameters for this service" page. Every time we try to load it, there is an error: "Internal error: static_checks:dell_powervault_me4_ports."

This issue affects the fan, FRU, port, power supply, status, and application services. It only works for the disk.

[Checkmk_Crash_monitoring_1acc76a2-4925-11ef-93d7-005056808711_2024-07-23_20-55-33.tar.gz](https://github.com/user-attachments/files/16353416/Checkmk_Crash_monitoring_1acc76a2-4925-11ef-93d7-005056808711_2024-07-23_20-55-33.tar.gz)

**Comment by Yogibaer75** [comment]
That's correct. As there are no rulesets present at the moment for these components.
The disk check uses the normal temperature ruleset.
If i have some time the rules need to be created.

**Comment by raafcioo** [comment]
I understand, thank you very much for the response.

Could you suggest if there is another way to add rules? I would like to receive notifications about changes in the status of network ports.

**Comment by Yogibaer75** [comment]
The port state is used as it comes from the device itself.
```
    port_states = {
        0: ("OK", 0),
        1: ("Degraded", 1),
        2: ("Fault", 2),
        3: ("Unknown", 3),
        4: ("Disconnected", 0),
    }
```
With these different states a notification should be no problem.
It is only not possible to "rewrite" some states if you mean this.
All the other checks use the state information from the device, if available.
