### ISSUE TITLE
[Feature Request] FortiGate Update: New option in rule configuration

### ISSUE THREAD

**Issue by JF-JX** [Yogibaer75/Check_MK-Things#74]
Hey there,
I have an idea how to improve this plugin: https://github.com/Yogibaer75/Check_MK-Things/tree/master/check%20plugins%202.3/fortigate_update
Currently, the only parameter you can set in the rule is "Days since last update" (or completely disable levels). In my case, this leads to a lot of warnings/criticals, although there are simply no updates available.
For example: "Last update 2024-08-01 (Warn/Crit: 30 days 0 hours/90 days 0 hours) Update typ: scheduled - Version: 24.00071 - Last contact: 2024-09-02 - Last result: No Updates"
It would be nice if there was a rule parameter like "State in case of 'no updates'", so that the services dont show an alert if there are no updates available, no matter when the last update occured.
Let me know what you think of that :)

**Comment by Yogibaer75** [comment]
Would it also be enough if i take the same levels for the "Last contact" and if the result of the last contact is "No Updates" then it is ok?

**Comment by JF-JX** [comment]
Yes, if the result of the last contact was "No Updates" then the state should be okay.

**Comment by Yogibaer75** [comment]
I uploaded a new version with commit 3a32d61
If the last state is "No Updates" or "Updates installed" and the last contact time is not older than the defined thresholds the check will be ok.
