### ISSUE TITLE
Upgrade HPE_ILO for 2.3.0pxx

### ISSUE THREAD

**Issue by 47k** [Yogibaer75/Check_MK-Things#78]
Please make the HPE_ILO plugin work under versions over 2.3.0pxx:

-| [hpe_ilo 4.0.2]: Uninstalling: Package requires Checkmk version below 2.3.0b1 (this is 2.3.0p20)

**Comment by systeembeheerder** [comment]
Did you see https://github.com/Yogibaer75/Check_MK-Things/tree/master/check%20plugins%202.2/hpe_ilo ?

_This package is obsolete please use the redfish package here_

**Comment by 47k** [comment]
No! I will use that, thank you! :)
