### ISSUE TITLE
Redfish: Discovery Rule for physical Ports

### ISSUE THREAD

**Issue by JF-JX** [Yogibaer75/Check_MK-Things#79]
Hey there,
Not sure if this is a good idea and if it's possible to implement this (or if thats already implemented):
I have a lot of "Physical Port xy" Services where the service output is "Link: LinkDown.." so I don't really care about these ports, but I can't disable them via regex because I have like 400 servers and the port names are always different ofcourse and doing this manually is not an option.
So my Idea was to create a service discovery rule where I can choose between "discover all ports" and "discover only ports where the Link is up". This would also save me some license cost :)
In case a port gets connected later, the discovery service would inform me and depending on the service discovery configuration automatically add the port to the monitoring.
Looking forward to your feedback!

**Comment by Yogibaer75** [comment]
Here i must look at the data if it is possible like i do it with network adapters.
They have a dedicated state if not present or absent.
What typ of check is this in your case?
- ethernetinterfaces
or
- networkports

**Comment by JF-JX** [comment]
I am talking about the "redfish_ethernetinterfaces" checks (sorry I didn't mention that).

**Comment by Yogibaer75** [comment]
OK i will look into this the next days. If the status is available as a dedicated state then it should be possible without bigger changes.

**Comment by JF-JX** [comment]
Thanks, let me know if I can help you!

**Comment by Yogibaer75** [comment]
Discovery option is now implemented with commit 0070c11
and version 2.3.66
