### ISSUE TITLE
redfish ilo cmk/os_platform label

### ISSUE THREAD

**Issue by systeembeheerder** [Yogibaer75/Check_MK-Things#80]
Looks like the redfish plugin adds automatic label to the host, which is good but can be done better imho

![image](https://github.com/user-attachments/assets/aafaafc8-d327-4521-acbe-c7bae8192514)

wouldn't it be better to keep the version out of it?

https://docs.checkmk.com/latest/en/labels.html#automatic_host_labels describes ``cmk/os_platform`` as

> Operating system platform, reported by the agent as OSPlatform (e.g. Ubuntu for Ubuntu derivatives such as Xubuntu)

there is a label ``cmk/os_version``  

> Operating system version, reported by the agent as OSVersion (e.g. 22.04 for Ubuntu or 10.0.19045 for Windows)

wouldn't that be a better place ?

**Comment by Yogibaer75** [comment]
Can you please check with the lastest version of the MKP.
I implemented the proposed changes with these version.
Now it looks like this.
![image](https://github.com/user-attachments/assets/7f22ecfb-71fc-44ce-8947-aa4016d012bc)

**Comment by systeembeheerder** [comment]
Just updated the plugin form 2.3.60 -> 2.3.65 and it works!

iLO4
![image](https://github.com/user-attachments/assets/6d598995-0056-4eb9-98c9-e20ca8e60c8b)

iLO5
![image](https://github.com/user-attachments/assets/ab88c8bf-3066-43d3-bd95-9346ca0af8f4)


Thanks again for your work on this plugin.
